### ISSUE TITLE
On module 4 (and lab), a link is broken

### ISSUE THREAD

**Issue by rlespinasse** [sfeir-open-source/sfeir-school-terraform#10]
The broken link is https://vimawesome.com/plugin/vim-terraform-state-of-grace

**Comment by jnahelou** [comment]
All the website [https://vimawesome.com/](https://vimawesome.com/) is down :/

**Comment by rlespinasse** [comment]
Maybe it's temporary 🤞

**Comment by jnahelou** [comment]
It works now :)
