### ISSUE TITLE
In lab6, replace vault with one cloud's secret manager

### ISSUE THREAD

**Issue by billietlsfeir** [sfeir-open-source/sfeir-school-terraform#165]
Google has secret manager, AWS has secrets manager, Azure has key vault.
In order to make this lab lighter and stop making the attendees deploy a k8s cluster with consul and vault inside, we could leverage one cloud's secret manager.

**Comment by jnahelou** [comment]
In #166 ,I added a section to use a existing cluster for all students.

Trainer can create the cluster using vault cloud, then init kv like :
```
$ alias vault-training='VAULT_ADDR=https://test-vault-cluster.vault.xxxx.aws.hashicorp.cloud:8200 VAULT_NAMESPACE=admin vault $@'
$ echo '<token>' | vault-training login -
$ vault-training secrets enable -path secret kv
```
