### ISSUE TITLE
On module 5, inspec version still need to be forced?

### ISSUE THREAD

**Issue by rlespinasse** [sfeir-open-source/sfeir-school-terraform#19]
As said in the `README.md` file of the `module-5`, the `inspec` is forced into a specific version because of a specific issue, but this issue inspec/inspec#4562 is closed now.

The `inspec` version can be updated?

**Comment by jnahelou** [comment]
It has been fixed in 4.18.51 but there is an other regression in 4.18.85.
I keep the issue open, an update here when inspec/gcp Gemfile will be upgraded.

**Comment by Ameausoone** [comment]
Fixed

**Comment by rlespinasse** [comment]
@Ameausoone thanks
